### ISSUE TITLE
Mp2/1 problem.

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#1]
Please look below.

**Comment by made101** [comment]
I corrected it. The co-ordinates were wrong in the game 1 and game 2. 
But I also faced another problem, It accidentally clicks on the blueprint button and then stops. It also says there is no fuel in a particular car but it shows that it has fuel. The script Just doesn't recognise it.

**Comment by made101** [comment]
I corrected that also but took me some time to figure out. If anyone from the future is here looking at this, I corrected the first issue by going to game1of1 and game2of2 and changing the coordinates just a tad bit. The issue 2, I corrected it by changing the '+' value of vehicle spacing by changing Its value to 1 instead of 7. 
At last, Thank you for the script.

**Comment by Made101** [comment]
The MP2 still doesn't work. Mp1 and carHunt work quite good.
I still need to find the solution for MP2. In Mp2, It isn't able to select the cars. If you edit and put ordinary, it'll race 10 times with 2 cars and then give "the car has no fuel" for the rest of the cars and the rest of them don't work not even the up and down ones. If you find a solution, please write me back.

**Comment by Made101** [comment]
![Screenshot_20210426-174625_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/116081061-680f6f00-a6b7-11eb-9fbd-bcace06bfd9a.jpg)
![Screenshot_20210426-174616_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/116081078-6c3b8c80-a6b7-11eb-86d9-6e5541c5b2f8.jpg)
The car hunt has been shifted and the script is not able to select it. Can you please guide me what needs to be done so that the script can automatically swipe and select the carhunt event? @yaldabaoth444

**Comment by Made101** [comment]
@yaldabaoth444 also in MP2 the script says no fuel to every other car except the first two even if they have fuel.

**Comment by yaldabaoth444** [comment]
Привет, извини за задержку в ответе.
Обновил play.js и в profile.js вроде бы тоже что то новое есть 
охоту теперь можно указывать с конца, например carHuntPosition: -8 - значит 8ая кнопка справа
Насчёт свайпа, есть небольшая зависимость величины сдвига и скорости перемещения и еще например 30 или 60fps тоже влияет (возможно быстродействие смартфона оказывает какое-то влияние). 
Я настраиваю следующим способом:
Запускаю такой скрипт
![image](https://user-images.githubusercontent.com/25618671/116789715-a4810780-aac9-11eb-929f-ff54eccbac21.png)
предварительно надо зайти в выбор авто, нажать например на серебряную лигу и я еще приклеваю стикер на перекрестие бензобака (например нижняя левая машина)
![image](https://user-images.githubusercontent.com/25618671/116790397-52da7c00-aacd-11eb-869d-1020428c8897.png)
В скрипте PLAY.adjustSwipe(20, 1500); - означает выбрать 20 машину, 1500 параметр из профиля (garage.swipeDuration: 1500) за какое время в миллисекундах происходит свайп. После отработки скрипта по стикеру определяем перебор или недобор и корректируем параметр distance: { x: 694 + 25, ... } и distanceFlat: { x: 712 + 25, ... }
У меня +25 на 30фпс и +30 при 60фпс

**Comment by yaldabaoth444** [comment]
Режим выбора машин регулируется параметром carPickMode
ordinary -это обычный режим с лигами bronze/silver/...
![image](https://user-images.githubusercontent.com/25618671/116790782-9df58e80-aacf-11eb-8120-6d792a231f77.png) 
или  
![image](https://user-images.githubusercontent.com/25618671/116790795-ad74d780-aacf-11eb-96f9-b3b3643619ef.png)
набор машин для каждой лиги задается (например для первой сети так)
![image](https://user-images.githubusercontent.com/25618671/116790903-4b68a200-aad0-11eb-945b-c77db6715640.png)

**Comment by yaldabaoth444** [comment]
flat - заданный событием список машин (например в охоте), сплошняком (без разделения на лиги). В этом режиме скрипт сначала пытается сделать сдвиг вправо, чтобы оказаться у первой машины и потом только начинает свайпать по номеру

**Comment by yaldabaoth444** [comment]
none - без выбора (обычно вторая сеть, с заданной машиной)

**Comment by yaldabaoth444** [comment]
up или down - режим в охоте, когда при выборе машин происходит позиционирование на последнюю машину на которой происходил заезд, соответственно выбираем верхнюю или нижнюю

**Comment by Made101** [comment]
Thank you, I adjusted it.

**Comment by Made101** [comment]
> Hi, sorry for the delay in reply.
> I updated play.js and in profile.js it seems that there is also something new, there is a
> hunt, now you can specify from the end, for example carHuntPosition: -8 - this means the 8th button on the right
> As for the swipe, there is a slight dependence of the magnitude of the shift and the speed of movement, and for example 30 or 60fps also affects (perhaps the speed of the smartphone has some effect).
> I set it up in the following way: I
> run such a script first, you need to go to the car selection, click, for example, on the silver league and I also stick a sticker on the crosshair of the gas tank (for example, the lower left car)
> ![image](https://user-images.githubusercontent.com/25618671/116789715-a4810780-aac9-11eb-929f-ff54eccbac21.png)
> 
> ![image](https://user-images.githubusercontent.com/25618671/116790397-52da7c00-aacd-11eb-869d-1020428c8897.png)
> In the script PLAY.adjustSwipe (20, 1500); - means to select 20 car, 1500 parameter from the profile (garage.swipeDuration: 1500) in what time in milliseconds the swipe takes place. After working out the script by the sticker, we determine the overkill or undershoot and adjust the distance parameter: {x: 694 + 25, ...} and distanceFlat: {x: 712 + 25, ...}
> I have +25 at 30fps and +30 at


When I enter Daily events, it swipes 5 times. I want it to swipe 3 times. Which value should I change in that case?

**Comment by yaldabaoth444** [comment]
If the event is placed on the first screen, it is better to specify a positive value
![image](https://user-images.githubusercontent.com/25618671/116810424-2cfcb800-ab5d-11eb-83c2-0b2a006f3601.png)
If the event does not fit on the first screen, you must specify a negative value and count down from the end
![image](https://user-images.githubusercontent.com/25618671/116810457-54538500-ab5d-11eb-8e49-2f098f908852.png)

**Comment by yaldabaoth444** [comment]
The number of swipes is set here
![image](https://user-images.githubusercontent.com/25618671/116810575-f3787c80-ab5d-11eb-9848-13d5f70cfb7a.png)
presumably 5 swipes should overlap the possible number of events in the future

**Comment by Made101** [comment]
> The number of swipes is set here presumably 5 swipes should overlap the possible number of events in the future
> ![image](https://user-images.githubusercontent.com/25618671/116810575-f3787c80-ab5d-11eb-9848-13d5f70cfb7a.png)

I tried to change the number to 4 but it still swipes 5 times, Not that I have any problem with it. The scripts work good. I just wanted to know which value I need to change to make a difference in swipes.

**Comment by yaldabaoth444** [comment]
I looked again carefully, you need to change the code on line 1058.  This piece of code can be replaced by a function call, apparently this has not been done yet.
![image](https://user-images.githubusercontent.com/25618671/116812338-ccbf4380-ab67-11eb-9356-4748cdb78556.png)

**Comment by Made101** [comment]
> I looked again carefully, you need to change the code on line 1058. This piece of code can be replaced by a function call, apparently this has not been done yet.
> ![image](https://user-images.githubusercontent.com/25618671/116812338-ccbf4380-ab67-11eb-9356-4748cdb78556.png)

Thank you, This worked. Also, How do you record your gameplay while running the script? My recorder just stops after auto.js asks permission for capturing the screen.

**Comment by yaldabaoth444** [comment]
I also failed to record video. There must be a conflict at the overlay level

**Comment by Made101** [comment]
> I also failed to record video. There must be a conflict at the overlay level

The latest version of Auto.js(8.7.8) is on Playstore. It is a paid application, however. Will there be any problems if I use that version instead of Auto.js 4.1.0?

**Comment by yaldabaoth444** [comment]
There may be differences in calls to basic functionality. You can only find out by trying. Let me know what happens after you try it.

**Comment by yaldabaoth444** [comment]
By the way, what values did you set for the parameter garage.swipeDuration and distance delta? Perhaps statistics on them will help to work out universal values

**Comment by yaldabaoth444** [comment]
You can also comment out line 284 `PressNitro()` in the play.js file. This was done for slipstream mode (for flash nitro)

**Comment by Made101** [comment]
> By the way, what values did you set for the parameter garage.swipeDuration and distance delta? Perhaps statistics on them will help to work out universal values

garage.swipeDuration is 1500(default). Delta for both eventsMarker and pagesMarker is also default. garage.distance I changed it to 30 instead of 26 since mine is 60fps. and same for distanceFlat, I changed it to 696 + 30.

**Comment by yaldabaoth444** [comment]
Great, I have the same settings

**Comment by Made101** [comment]
> Great, I have the same settings

I'll tell you the changes I changed to adjust the script for the arrinera hunt. Since you replied after the hunt, I had to adjust it myself. I'm a rookie in javascript, so it took me some time to figure out.

Profile and play.js are both the old ones. The new play.js and profile.js(which you updated yesterday I changed their name to profile1 and play1 just for this video). 
I called the function you set for choosing cars in multiplayer and changed value of x and y in the robots.swipe command.

![Screenshot (73)_LI](https://user-images.githubusercontent.com/77076813/116822817-a072e980-ab9e-11eb-8cd0-cf9d615ad56b.jpg)

The swipe is slower than the one you made but It got me through the hunt without any problems. 
I placed it under case"home" of switch(chstatus).
I also changed to pressXOffset accordingly(sometimes +100, sometimes +200)
Saved settings and then tested the script.

[Settings changed and run script](https://youtu.be/9A8jR9Z01EQ)

It does not matter now, since, I use the swipe you made which is much better than this.

**Comment by yaldabaoth444** [comment]
The highlighted fragment in the screenshot is responsible for shifting the cars in the garage by the required number of times. (pixel-by-pixel accuracy is important there) When you swipe, the speed and magnitude of the shift matter, which affects some attenuation of the inertia of the shift. I tried playing around with the parameters to come up with some universal values.
And the function that shifts events doesn't have to be that accurate. Its main task is to scroll the list all the way to the end

**Comment by yaldabaoth444** [comment]
You can write in Russian, it's my native language, just like yours, I guess

**Comment by Made101** [comment]
> You can write in Russian, it's my native language, just like yours, I guess

Nah, lad. I'm not russian, I just set the language to Russia so that the script works just like yours. I thought, If I kept the game language English, it may give some Errors.

**Comment by Made101** [comment]
> The highlighted fragment in the screenshot is responsible for shifting the cars in the garage by the required number of times. (pixel-by-pixel accuracy is important there) When you swipe, the speed and magnitude of the shift matter, which affects some attenuation of the inertia of the shift. I tried playing around with the parameters to come up with some universal values.
> And the function that shifts events doesn't have to be that accurate. Its main task is to scroll the list all the way to the end

Thank you for this. Now, I understand.

**Comment by yaldabaoth444** [comment]
Perhaps when you change the language, some elements, such as buttons and dialog boxes will have a different size and will have to adjust the values. The basic parameters of the profile are described here Asphalt9/readme/Explanation of settings in pictures/

**Comment by Made101** [comment]
> Perhaps when you change the language, some elements, such as buttons and dialog boxes will have a different size and will have to adjust the values. The basic parameters of the profile are described here Asphalt9/readme/Explanation of settings in pictures/

Yeah. I did that just to be extra safe, So that I don't encounter any unnecessary errors.

**Comment by yaldabaoth444** [comment]
Have fun racing

**Comment by made101** [comment]
@yaldabaoth444 My script is not able to select the upper cars(15,17,19,13). It is selecting only lower cars(8,10,12). Can you please look into it if something is wrong. I restarted the device twice and it still has the same problem.
