### ISSUE TITLE
Feature request: handle network connection issues

### ISSUE THREAD

**Issue by nujabse** [yaldabaoth444/Asphalt9#10]
Thanks a lot for such brilliant Auto. js script for A9. I've been using it for quite a while. However, sometimes, the network connection is slow or the game server can not be reached:
![image](https://user-images.githubusercontent.com/9455367/151386527-1393aa56-7d4c-4de2-8810-520977cdfbea.png)

Can the script make some retries or just quit the game when under such conditions?

**Comment by yaldabaoth444** [comment]
Hi, thanks for participating 👍. Try adding the button image to this directory
![image](https://user-images.githubusercontent.com/25618671/151491088-2ffaba4f-1f8e-4d01-9674-6db8065900ee.png)

**Comment by nujabse** [comment]
Thanks for the reply. I'll give it a try.
