### ISSUE TITLE
Car hunt not working

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#11]
Hey there
My normal car hunt and the special event tab car hunt, both are not working.
When I start the main.js file, it doesn't click anything
And when I went to check the logs, it was like this
![Screenshot_20220213-203004](https://user-images.githubusercontent.com/77076813/153759227-9f77cbf5-9e38-47a1-b64f-f92790c9fe0e.jpg)
Can you please see what's wrong here?

**Comment by yaldabaoth444** [comment]
the interface in the current hunt has changed, and while the hunt in the special event is not working

**Comment by yaldabaoth444** [comment]
But regular hunting should work
