### ISSUE TITLE
Bug report: the car hunt will be stuck when catHuntPosition is 9

### ISSUE THREAD

**Issue by nujabse** [yaldabaoth444/Asphalt9#12]
There are quite a few daily events recently, which makes the car hunt event become the 9th event in the daily events. However, when I set the `carHuntPosition` equal to 9, the script will be stuck at the daily events page. I think this might be related to that the script can not swipe in the daily events pages, making it unable to handle a high index number. Maybe we can add a swipe function here?

**Comment by yaldabaoth444** [comment]
added a shift of events to the left, for a positive position greater than 8

**Comment by yaldabaoth444** [comment]
1989th line in play.js (func pressMarkerButton)

**Comment by nujabse** [comment]
Thanks for the quick fix, now the car hunt event can be selected successfully.
