### ISSUE TITLE
Bug report: mp2 can not be started if huntCounts are set

### ISSUE THREAD

**Issue by nujabse** [yaldabaoth444/Asphalt9#13]
After the latest update (released on April 6, 2022, version **3.4.5a**), the multiplayer 2 can not be started if `huntCounts` are set greater than 0. The script will always start multiplayer 1 not playing multiplayer 2. It will play multiplayer 2 normally if I set `huntCounts` to `0`.

**Comment by yaldabaoth444** [comment]
you need to set 
var mp2Counts = 0;
var mp2EveryMinutes = 30;

**Comment by yaldabaoth444** [comment]
you need to find the right ratio between ... hunt | mp1 | mp2

**Comment by nujabse** [comment]
Thanks for your suggestions, it's working now.
