### ISSUE TITLE
Адаптация разрешения

### ISSUE THREAD

**Issue by Dexya** [yaldabaoth444/Asphalt9#14]
Приветствую!
Помогите пожалуйста адаптировать разрешение под мой телефон 2280x1080

**Comment by yaldabaoth444** [comment]
Привет, вы посмотрели картинки в этом разделе https://github.com/yaldabaoth444/Asphalt9/tree/master/readme/Explanation%20of%20settings%20in%20pictures ?

**Comment by yaldabaoth444** [comment]
вам нужно заменить в файле profile.js строки такого вида token: { x: 1482, y: 54, color: '#0090ff' }
Нужно делать скриншоты в формате png (чтобы не было потерь в цветопередаче)
Принцип работы такой. Есть функции вида mpCheckState, chCheckState, которые анализируют данные метрики и на основании них определяют на каком экране находится бот.

**Comment by yaldabaoth444** [comment]
Для удобства нужно создать дополнительный файл например test.js такого содержания
![image](https://user-images.githubusercontent.com/25618671/163992776-003e6fe8-105e-4ce5-a415-bfc82569814c.png)

**Comment by yaldabaoth444** [comment]
и в нужных местах запускаете его.
Он выдаст отладочную инфу (Будет видно какие метрики он видит на данном экране)
там такой код 
![image](https://user-images.githubusercontent.com/25618671/163993024-e533ff81-36cd-4416-a97d-c12e1d2433c4.png)
что то типа такого mpCheckState Token Credit Back Game2 Network Race Dialog

**Comment by yaldabaoth444** [comment]
сами картинки я делал давненько, возможно там не всё вынесено в профиль
Ну или вариант 2) сделать скриншоты всех экранов, залить в облако и ссылку киньте сюда

**Comment by yaldabaoth444** [comment]
какие нужны скриншоты? Правило примерно такое, во время игры если вы хотите нажать/свайпнуть чтолибо, перед эти надо сделать скриншот. Скрины из гаража, одну тачку с полностью пустыми звездами, и одну с полностью заполнеными + тачки разных классов DCBAS. Скрин из гонки. Скрины с всплывающими диалогами (ошибки/повышение лиги/ и т.д). Не нужно каждый закоулок в игре скринить только, только то что относится к мультиплееру и охоте

**Comment by Dexya** [comment]
> какие нужны скриншоты? Правило примерно такое, во время игры, если вы хотите примерить/свайпнуть что-либо, перед этим надо сделать скриншот. Скрины из гаража, одну тачку с полностью пустыми звездами, и одну тачку с полностью заполненными + тачки разных классов DCBAS. Скрин из гонок. Скрины с Окончательными диалогами (ошибки/повышение лиги/ и т.д). Не нужно каждый закулок в игре скринить только, только то что относится к мультиплееру и охоте

Скрин повышения для каждой лиги нужен? Или подойдёт только 1 из бронзы в серебро, например?

**Comment by yaldabaoth444** [comment]
повышение и понижение вроде

**Comment by yaldabaoth444** [comment]
возможно многое совпадёт, хз, вроде только ширина отличается

**Comment by Dexya** [comment]
https://disk.yandex.ru/d/Ra-xD51lsn1eRg
Надеюсь все правильно сделал

**Comment by yaldabaoth444** [comment]
jpg не пойдёт, там цвета пикселей искажены сжатием. я же выше писал. надо чтобы телефон сразу в png записывал скриншоты. в опциях гдето переключается. загугли

**Comment by yaldabaoth444** [comment]
[_screenshot.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8514590/_screenshot.js.txt)
вот можно такой скрипт запускать. расширение txt только убери

**Comment by yaldabaoth444** [comment]
нужен такой скрин еще
![image](https://user-images.githubusercontent.com/25618671/164076045-8f5699ce-d301-4f69-8976-fed6fe566053.png)
без сдвига машин

**Comment by yaldabaoth444** [comment]
еще такой же без разделения на лиги, но пока такой сетки нет

**Comment by yaldabaoth444** [comment]
6* тачки нет
![image](https://user-images.githubusercontent.com/25618671/164077728-6da131b1-2e76-4897-9702-b3b2146037e5.png)
нади в событиях такую, если свои не прокачаны

**Comment by yaldabaoth444** [comment]
делаю пока по jpg в большинстве случаев конечно сравнение с допуском происходит, может прокатит

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164078354-5cb78c39-9abb-4e13-bb9a-bdd5f6482555.png)
есть только D и S класс, нужны остальные

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164081344-b2b3b711-6e06-4ef9-962d-14a20a7ac18f.png)
еще такой скрин из мультиплеера

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164081964-0dfffec3-ad8c-402b-911f-a57989b150a0.png)
и такой. они нужны чтобы определять доступна ли машина для гонки. "Пропустить" и "Добудь чертежи" есть

**Comment by Dexya** [comment]
https://disk.yandex.ru/d/Ra-xD51lsn1eRg
Перескринил в png

**Comment by yaldabaoth444** [comment]
ок, щас гляну, недостающие еще сделай

**Comment by Dexya** [comment]
https://disk.yandex.ru/d/h5CGcFOhfbHzCA
Недостающие скрины

**Comment by yaldabaoth444** [comment]
тачки B и A класса нет, и 6* тачки

**Comment by Dexya** [comment]
https://disk.yandex.ru/d/h5CGcFOhfbHzCA
Добавил.
Не загрузились по какой то причине

**Comment by yaldabaoth444** [comment]
[profile.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8516510/profile.js.txt)

**Comment by yaldabaoth444** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8516512/play.js.txt)

**Comment by yaldabaoth444** [comment]
[mp1infinite.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8516513/mp1infinite.js.txt)
пока проверяем мультиплеер

**Comment by yaldabaoth444** [comment]
еще нужно самому заменить знаки в папке TrafficSigns
ramp, ramp_left, ramp_right
но и так должно работать (просто он их находить не будет)
хотя я уверен что сразу не заработает

**Comment by yaldabaoth444** [comment]
[test.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8516530/test.js.txt)
позапускай такой файл на основных экранах

**Comment by yaldabaoth444** [comment]
он должен распознавать кнопку назад, токены и кредиты видеть если они видны

**Comment by yaldabaoth444** [comment]
режим выбора машин лучше использовать ordinary-abc, flat-abc и none
другие я сам уже не использую и их настраивать муторно

**Comment by yaldabaoth444** [comment]
ошибки в auto.js можно в логе глянуть

**Comment by Dexya** [comment]
11:05:26.802/E: SyntaxError: missing } after property list
    at Require (file:///android_asset/modules/jvm-npm.js:121:0)
    at /storage/emulated/0/脚本/asphalt/main.js:2:0
Что то я делаю не так. Логически подумав я где то скобку пропустил?

**Comment by yaldabaoth444** [comment]
main.js еще рано запускать. test.js отрабатывает?
что это за каталог /脚本/asphalt? у меня прямо в 脚本 лежит

**Comment by yaldabaoth444** [comment]
может в profile.js где то скобку забыл. те что я тебе сюда выложил я синтактических ошибок не вижу

**Comment by yaldabaoth444** [comment]
можно попробовать play.js запустить напрямую, хотя там нечему запускаться он ругнётся если ошибки синтактические есть

**Comment by Dexya** [comment]
asphalt - папка со скриптами
Сейчас буду пробовать, ковыряться

**Comment by yaldabaoth444** [comment]
/\*!\*/ Я такие отметки в profile добавлял у значений которые менял

**Comment by Dexya** [comment]
/E: SyntaxError: missing } after property list
    at Require (file:///android_asset/modules/jvm-npm.js:121:0)
    at /storage/emulated/0/脚本/asphalt/test.js:4:0
Test.js ругается такой же ошибкой

**Comment by yaldabaoth444** [comment]
найди в файле profile.js строку 
goldenPoint: { x: 2106, y: 917, color: '#c3fb12' },
сравни с этим

**Comment by yaldabaoth444** [comment]
запятые все есть?

**Comment by yaldabaoth444** [comment]
https://esprima.org/demo/validate.html в валидатор можешь загнать содержимое и проверить

**Comment by Dexya** [comment]
> найди в файле profile.js строку goldenPoint: { x: 2106, y: 917, color: '#c3fb12' }, сравни с этим

Да, запятой не хватало.
test.js работает нормально

**Comment by yaldabaoth444** [comment]
попробуй теперь запустить mp1infinite.js

**Comment by Dexya** [comment]
![image](https://user-images.githubusercontent.com/90963419/164231395-0fddf0d6-459c-4028-848f-7ac8f092ca13.png)
Зашел в мультиплеер - Выбрал верхнюю сеть - выбрал серебряную лигу - выбрал машину в серебре - отмотал машины назад - начал гонку и ошибка, но она я так понимаю, потому что еще не добавил никаких картинок

**Comment by Dexya** [comment]
Сейчас закину их, включу еще разок

**Comment by yaldabaoth444** [comment]
знаки регулируются здесь
![image](https://user-images.githubusercontent.com/25618671/164233162-4eff3801-ef74-4117-acad-bf7f83030ae4.png)

**Comment by Dexya** [comment]
Они должны находиться в папке где скрипты - Images/TrafficSigns ?

**Comment by yaldabaoth444** [comment]
скачай полностью весь проект, там же уже все папки созданы

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164251621-b62e9ea3-39bc-4910-9d78-27764d64be4f.png)

**Comment by yaldabaoth444** [comment]
> Они должны находиться в папке где скрипты - Images/TrafficSigns ?

да

**Comment by Dexya** [comment]
Так, есть. Мультиплеер работает. Рампы теперь выбирает

**Comment by yaldabaoth444** [comment]
класс

**Comment by yaldabaoth444** [comment]
2 сеть тоже должна работать

**Comment by yaldabaoth444** [comment]
[mp2infinite.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8523027/mp2infinite.js.txt)

**Comment by yaldabaoth444** [comment]
[carHunt5.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8523037/carHunt5.js.txt)

**Comment by yaldabaoth444** [comment]
если всё заработает значит main.js тоже будет работать

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164271348-16e392ed-e7b3-4e94-8b58-dd889578bb59.png)
вот еще нужно подправить для охоты

**Comment by yaldabaoth444** [comment]
потом можно проверить ограничение по класссам срабатывает или нет, например в охоте выставить [C5] или в сети на своё усмотрение

**Comment by Dexya** [comment]
Нижняя сеть играет, но выскакивает ошибка, я так думаю слишком быстро он ищет рампы. Охота выбирает тачку и пролистывает все подряд почему то

**Comment by yaldabaoth444** [comment]
что за ошибка? надо протестить фнукции определения класса и звездности  у авто

**Comment by yaldabaoth444** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8524498/play.js.txt)

[test.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8524488/test.js.txt)

**Comment by yaldabaoth444** [comment]
попробуй test позапускать в том месте где машины пролистываются, скрипт должен показать какую машину он видит

**Comment by Dexya** [comment]
> что за ошибка? надо протестить фнукции определения класса и звездности у авто

![IMG_20220421_004400_660](https://user-images.githubusercontent.com/90963419/164301140-187501ae-643e-43f0-9395-3a0fc8364a71.jpg)

**Comment by Dexya** [comment]
> попробуй тест запустить в том месте где машина пролистывается, скрипт должен показать какую машину он видит

Все классы машин видит

**Comment by yaldabaoth444** [comment]
на охоту такие настройки? 

var chCarPickABC = ['D4'];

ch:{
         carPick : chCarPickABC,

**Comment by Dexya** [comment]
D3, D4

**Comment by yaldabaoth444** [comment]
достаточно D3 указать (это минимум указывается) D3 и выше

**Comment by yaldabaoth444** [comment]
ошибка странная, она только во 2 сети выскакивает? в каждой гонке?

**Comment by Dexya** [comment]
> ошибка странная, она только во 2 сети выскакивает? в каждой гонке?

Нет, не в каждой. Может 3 гонки сыграть, может 5, или вообще 1
Да, только во 2 сети, в 1 не было такого. Сейчас ещё поставлю посмотрю

**Comment by yaldabaoth444** [comment]
а что за телефон у тебя, кто то переменную зачищает, в которой скрин экрана хранится хотя она только что сделана. памяти у тебя сколько?

**Comment by yaldabaoth444** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8524745/play.js.txt)
нашёл вроде почему тачка не выбиралась в режиме flat-abc.

**Comment by Dexya** [comment]
> а что за телефон у тебя, кто то переменную зачищает, в которой скрин экрана хранится хотя она только что сделана. памяти у тебя сколько?

Mi 8 lite на него ставится скрипт. 4 гб

**Comment by yaldabaoth444** [comment]
> 

вроде норм

**Comment by Dexya** [comment]
Да, Охота заработала.
Появилась проблема что эта ошибка и в 1 сети и в охоте появляется

**Comment by yaldabaoth444** [comment]
сделай еще раз скрин ошибки, а то строки сбились

**Comment by yaldabaoth444** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8525088/play.js.txt)
погуглил их доки, попробуй такой вариант

**Comment by yaldabaoth444** [comment]
у тебя какая версия auto.js?

**Comment by Dexya** [comment]
> у тебя какая версия auto.js?

3.0.0

**Comment by Dexya** [comment]
Ну, 10 гонок он сделал и продолжает работать. Вечером поставлю на более длительное время. А что за ошибка это была? Я с ней сталкивался несколько месяцев назад, когда хотел поставить по поискам по картинкам скрипты, но так как некому было мне помочь и в силу своих знаний в этой теме оставил эту идею

**Comment by yaldabaoth444** [comment]
> > у тебя какая версия auto.js?
> 
> 3.0.0

чёт старовата, может из за этого ошибки. там ссылка есть на 4.1.1

**Comment by Dexya** [comment]
> > > у тебя какая версия auto.js?
> > 
> > 
> > 3.0.0
> 
> чёт старовата, может из-за этой ошибки. там ссылка есть на 4.1.1

Ошибка бывает, но реже теперь. Скачаю попробую

**Comment by yaldabaoth444** [comment]
у меня иногда часов по 10ч крутится беспрерывно. В последней охоте например: стоит MP2 + Hunt, с нуля тачку качаю. Ещё осталось 15 чертежей до Maxed.

**Comment by yaldabaoth444** [comment]
у меня кстати тоже бывают иногда ошибки, но это чтото с операционкой или с ядром auto.js связанно, например если бот долго работает бывают странные ошибки, но лечится перезагрузкой

**Comment by Dexya** [comment]
Вообще ещё грешу на то, что телефон хламом забит. Хочу его к заводским снести. На нем обычным кликером где то год пользовался. Ну и так всякая фигня на нем еще

**Comment by Dexya** [comment]
![IMG_20220421_141704](https://user-images.githubusercontent.com/90963419/164411323-d0bd4673-8604-416e-a483-3182c14c0819.jpg)
В охоте ругается, сетки вроде нормально едет.

**Comment by yaldabaoth444** [comment]
ты обновил auto.js? всё та же проблема с распознованием изображения

**Comment by yaldabaoth444** [comment]
таких моментов в скрипте очень много, придётся править много кода только чтобы работала старая версия auto.js

**Comment by yaldabaoth444** [comment]
везде где captureScreen() используется надо создавать локальную переменную и делать копию картинки
![image](https://user-images.githubusercontent.com/25618671/164412856-3a881ebf-0881-4cfb-8188-baa641076a7e.png)

**Comment by Dexya** [comment]
> ты обновил auto.js? всё та же проблема с распознованием изображения

Да, обновил

**Comment by yaldabaoth444** [comment]
ясно, ща поменяю

**Comment by yaldabaoth444** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8529175/play.js.txt)
поменял, надеюсь проблема была в этом

**Comment by Dexya** [comment]
В верхней сетке, кстати, как себя ведет? До платины, легенды доходит сам?)

**Comment by yaldabaoth444** [comment]
до легенды доходит виндовый бот, в андроиде золото-платина. Ну еще от типа зависит слип|ghost

**Comment by yaldabaoth444** [comment]
я опытным путём вывел что текущий набор знаков даёт в 90% нужный маршрут

**Comment by yaldabaoth444** [comment]
чтобы делать навигацию под каждую карту нужно распознавание делать (думал чтонибудь подобное запилить). Существующей функции подсчёта хеша я не нашёл. Плюс надо еще привяку к процентам трассы делать, а то текущая навигация привязана к времени.

**Comment by Dexya** [comment]
![IMG_20220421_202913](https://user-images.githubusercontent.com/90963419/164480614-399bf71e-3e9d-4134-aae9-67aaed163291.jpg)
Ругается опять(

**Comment by Dexya** [comment]
Именно в охоте, почему то

**Comment by yaldabaoth444** [comment]
а ты какие знаки сделал? у охоты же маршрут прописан

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164506338-1a05505c-b9cd-4f0c-ba74-9a60f04982bd.png)

**Comment by yaldabaoth444** [comment]
можно закоментить строку с навигацией, тогда будут дефолтные работать только

**Comment by Dexya** [comment]
Ой, чёт не то я нажал

**Comment by Dexya** [comment]
Да, Охота работает. Не дождался правда когда закончатся билеты. Начал искать почему в верхней сети выбирает только 1 авто (корвет д класса, но иногда переключается на фурай или хуракна) и говорит, что нет бензина. И во второй сети не выбирает верхние авто

**Comment by yaldabaoth444** [comment]
а он точно классы и звезды правильно определял?

**Comment by yaldabaoth444** [comment]
и что значит верхние? в режиме *-abc он не различает верх и низ

**Comment by Dexya** [comment]
> и что значит верхние? в режиме *-abc он не различает верх и низ

Ну, он нажимает два раза на пролистывает машины влево

**Comment by yaldabaoth444** [comment]
ну он нажимает пока не встретит авто с заданными параметрами

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164550254-f313659b-5e14-4b87-ae92-df8ea27f5f63.png)
он когда в сеть заходит определяет лигу, потом смотрит какие авто в этой лиге разрешены
![image](https://user-images.githubusercontent.com/25618671/164550799-7747343a-d694-46ff-b859-d2a4a5f04a0a.png)

**Comment by Dexya** [comment]
Но там выбраны все машины 
![IMG_20220422_025628](https://user-images.githubusercontent.com/90963419/164551045-1acb9a9e-f87c-42da-97a5-c0303b7a3487.jpg)

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164551107-14c6ce2f-9d24-4bb5-8e41-bbbe417cbc47.png)
возможно тут еще прочекать надо значения, там  вон платина еще не выставлена даже..походу я забыл про неё

**Comment by yaldabaoth444** [comment]
запустил 2 сеть, выбрал AF10
вроде норм

**Comment by Dexya** [comment]
У меня он заходит в сеть, выбирает Nio, откатывает на ней весь бензин, пропуская AF10 берет тайкана

**Comment by Dexya** [comment]
В верхней сетке звёздность и класс машин определяет нормально

**Comment by yaldabaoth444** [comment]
запусти test.js в AF10 должен выдать B3 (в моём случае)

**Comment by Dexya** [comment]
B4 выдал

**Comment by yaldabaoth444** [comment]
ну отличий не должно быть когда он уже тачки перебирает, они одинаковые где бы он их не выбирал

**Comment by Dexya** [comment]
Возможно, что телефон чуть фризит и скрипт нажимает на кнопку влево ещё раз?

**Comment by yaldabaoth444** [comment]
ну попробуй паузу увеличить в function hasFuelABC
там еще есть условие var canGo = 
можно скрин проблемной машины сделать и глянуть соблюдается ли условие
а пауза в самом конце 300мс

**Comment by yaldabaoth444** [comment]
я эту систему недавно добавлял и там еще есть значения не вынесенные в конфиг

**Comment by Dexya** [comment]
С 255 начиная, правильно?

**Comment by Dexya** [comment]
У меня в принципе на выборе машины на этом телефоне фризы проскакивают, так что думаю там везде можно паузу увеличить чутка

**Comment by yaldabaoth444** [comment]
255?

**Comment by Dexya** [comment]
Строка

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/164557063-97c55a55-b14f-4a5c-aecd-7013337200e6.png)
1423 примерно

**Comment by yaldabaoth444** [comment]
и в следующей функции тоже

**Comment by Dexya** [comment]
Да, это исправило проблему. 
А в верхней сети, что когда заканчивается бензин, он перестает работать есть мысли?

**Comment by yaldabaoth444** [comment]
было такое уже? добавь D класс они быстро заправляются

**Comment by yaldabaoth444** [comment]
> Да, это исправило проблему.

какую задержку выставил?

**Comment by Dexya** [comment]
> > Да, это исправило проблему.
> 
> какую задержку выставил?

1000мс

**Comment by yaldabaoth444** [comment]
ясно

**Comment by Dexya** [comment]
> было такое уже? добавь D класс они быстро заправляются

Это в Д классе. После разрядки первой же машины.

**Comment by yaldabaoth444** [comment]
там есть еще таймер на 2 минуты, с такой задержкой он не может не успевать все тачки перебрать.
140 тачек ...это выйдет на минуты 3 наверное

**Comment by yaldabaoth444** [comment]
> > было такое уже? добавь D класс они быстро заправляются
> 
> Это в Д классе. После разрядки первой же машины.

не очень понял ..в бронзе чтоль? в первой сетке?

**Comment by Dexya** [comment]
> > > было такое уже? добавь D класс они быстро заправляются
> > 
> > 
> > Это в Д классе. После разрядки первой же машины.
> 
> не очень понял ..в бронзе чтоль? в первой сетке?

Да, но проблема решилась тем же путем. Выставив задержку при выборе тачки ушла и эта

**Comment by yaldabaoth444** [comment]
пока ты вырабатываешь бензин у одно тачки Д класса, другие успевают перезаряжаться. Там двух тачек хватает на бесконечный фарм. Наверное ты не так проблему сформулировал

**Comment by Dexya** [comment]
Скорее всего. 
Скрипт откатывал только одну тачку, говорил, что кончился бензин и останавливался. Но сейчас все отлично

**Comment by Dexya** [comment]
И подскажи такой момент, где закоментить одну из функций (охоту, мп1, мп2)?

**Comment by Dexya** [comment]
И если я хочу убрать выбор знаков в мультиплеере, куда мне смотреть, чтобы сделать это?

**Comment by yaldabaoth444** [comment]
> И подскажи такой момент, где закоментить одну из функций (охоту, мп1, мп2)?

если ты про main,js то у каждого в начале есть *сounter'ы ..надо 0 поставить
у кого больше счётчик тот бы нагрузкой является (filler task). Обычно это MP1 (так как он может бесконечно работать), ну или может быть MP2 если там тачка бесконечная дана или есть хотябы пару тачек Д класса
Далее в них есть проверка не пора ли выполнять цикл более верхнего уровня (MP1 -> MP2 -> Hunt)
Охота автоматом вычисляется (так как скорость восстанавления билетов известна) MP2 время надо самому задавать и количество каток (так как они разные бывают) . Если в охоте тачка Д класса катает, я обычно 1 ставлю для Охоты.  ну и там дальше уже по ситуации надо смотреть. Главное чтобы цикл не прерывался из за нехватки бензина. Иначе игра по таймауту дисконектится. Хотя вроде если скрипт застревает надолго он будет рестартвать игру.

**Comment by yaldabaoth444** [comment]
> И если я хочу убрать выбор знаков в мультиплеере, куда мне смотреть, чтобы сделать это?

в конфиге mpSignSet, надо сделать пустым или вообще закоментить ...надо проверить. Я сам не пробовал просто

**Comment by Dexya** [comment]
> > И подскажи такой момент, где закоментить одну из функций (охоту, мп1, мп2)?
> 
> если ты про main,js то у каждого в начале есть *сounter'ы ..надо 0 поставить у кого больше счётчик тот бы нагрузкой является (filler task). Обычно это MP1 (так как он может бесконечно работать), ну или может быть MP2 если там тачка бесконечная дана или есть хотябы пару тачек Д класса Далее в них есть проверка не пора ли выполнять цикл более верхнего уровня (MP1 -> MP2 -> Hunt) Охота автоматом вычисляется (так как скорость восстанавления билетов известна) MP2 время надо самому задавать и количество каток (так как они разные бывают) . Если в охоте тачка Д класса катает, я обычно 1 ставлю для Охоты. ну и там дальше уже по ситуации надо смотреть. Главное чтобы цикл не прерывался из за нехватки бензина. Иначе игра по таймауту дисконектится. Хотя вроде если скрипт застревает надолго он будет рестартвать игру.

Ну да, допустим сейчас Охота на акуру началась, а она у меня есть, то в принципе можно и не катать. Так же и со второй сетью бывает

> > И если я хочу убрать выбор знаков в мультиплеере, куда мне смотреть, чтобы сделать это?
> 
> в конфиге mpSignSet, надо сделать пустым или вообще закоментить ...надо проверить. Я сам не пробовал просто

Фризы бывают на этом телефоне во время гонки, и туго в повороты входит, очень сильно теряет в скорости, хочу проверить будет ли он быстрее ехать, если будет ехать как ему даёт это делать игра

**Comment by yaldabaoth444** [comment]
я иногда отдельными файлами запускаю бесконечную MP1 или MP2, если такое необходимо, чтобы не редактировать main.js

**Comment by yaldabaoth444** [comment]
ты yt в ВЧТХ случаем?

**Comment by Dexya** [comment]
> ты не в ВЧТХ случаем?

Нет. Но рассматривал для вступления давно ещё)

**Comment by Dexya** [comment]
Я с FPC.

**Comment by yaldabaoth444** [comment]
норм вроде идёте

**Comment by yaldabaoth444** [comment]
удалим последние посты

**Comment by Dexya** [comment]
Не занимался просмотром паков? 
Это сейчас не актуально правда, но есть надежда что это вернут)

**Comment by Dexya** [comment]
> > И если я хочу убрать выбор знаков в мультиплеере, мне смотреть, чтобы сделать это?
> 
> в конфиге mpSignSet, надо сделать пустым или вообще закоментить ...надо проверить. я сам не пробовал просто

Закоментил, все нормально. Едет по автопути просто, 5 гонок откатал без проблем

**Comment by yaldabaoth444** [comment]
и что лучше стало?

**Comment by Dexya** [comment]
Да, что то вроде так же)

**Comment by yaldabaoth444** [comment]
вообще думаю распознавание может серьёзно проц нагружать, хотя по ощущениям на андроиде шустрее работает чем на винде

**Comment by yaldabaoth444** [comment]
с рампами бот не так сильно палится, только когда в повороты невписывается :)

**Comment by yaldabaoth444** [comment]
можно теоретически и подтормаживания добавить, но кажись результативность хуже в общем становится
таких трасс не так много

**Comment by Dexya** [comment]
Ну я год на обычном кликере сидел. Пока бананов не было :)

**Comment by yaldabaoth444** [comment]
банят в основном по времени, больше 20 часов в сутки если

**Comment by Dexya** [comment]
> можно теоретически и подтормаживания добавить, но кажись результативность хуже в общем становится таких трасс не так много

Я как то ставил с дрифтом обычный кликер. Он набирал нитроволну и использовал ее. До золота доходил. Обычный же автопуть всегда приводил только в серебро

**Comment by Dexya** [comment]
> банят в основном по времени, больше 20 часов в сутки если

Ну я в основном на ночь ставлю, редко по дню использую

**Comment by Dexya** [comment]
![IMG_20220422_125042](https://user-images.githubusercontent.com/90963419/164619528-8cc110e5-9bfd-4756-872f-b647af1e8294.jpg)
Что то у меня Охота на этом экране зависает

**Comment by yaldabaoth444** [comment]
а в логах что?

**Comment by Dexya** [comment]
![IMG_20220422_132828](https://user-images.githubusercontent.com/90963419/164627728-5a0c73e7-90a5-403f-a58e-43eb0cbfd662.jpg)

**Comment by Dexya** [comment]
Остановил я сам уже

**Comment by yaldabaoth444** [comment]
надо chCheckState опять проверить что говорит на этом экране

**Comment by Dexya** [comment]
![IMG_20220422_155610](https://user-images.githubusercontent.com/90963419/164683724-4c6bdc1c-f002-4417-91dd-14eef03363e7.jpg)

**Comment by yaldabaoth444** [comment]
chCheckState только надо

**Comment by yaldabaoth444** [comment]
по аналогии

**Comment by yaldabaoth444** [comment]
там надо в Play.js подправить название

**Comment by yaldabaoth444** [comment]
и потом еще надо будет toastLog("chCheckState " + chCheckState(false)); глянуть
goingHome нажимает "back" из этих состояний "start","events","hunt","dialog"
похоже что profile.ch.start не правильно установлен

**Comment by yaldabaoth444** [comment]
этот экран кажись start должен называться (когда без true будешь запускать)

**Comment by yaldabaoth444** [comment]
chCheckState(true) выдает только метрики
chCheckState(false) выдает название экрана (на основании комбинаций метрик)

**Comment by yaldabaoth444** [comment]
хотя непонятно как раньше работало

**Comment by Dexya** [comment]
Чёт не выходит у меня, дуб дубом я тут

**Comment by yaldabaoth444** [comment]
пришли свои файлы, чтобы то что ты менял не пропало

**Comment by yaldabaoth444** [comment]
carHunt5.js у тебя полностью отрабатывает? и застревает только при переходе от MP к Hunt?

**Comment by Dexya** [comment]
> carHunt5.js у тебя полностью отрабатывает? и застревает только при переходе от MP к Hunt?

Да

**Comment by Dexya** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8543454/play.js.txt)
https://github.com/yaldabaoth444/Asphalt9/issues/14#issuecomment-1106070626 застревает на этом дисплее

**Comment by yaldabaoth444** [comment]
а в main.js менял чтонибудь? тоже давай на всякий случай

**Comment by yaldabaoth444** [comment]
[play.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8543653/play.js.txt)
[test.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/8543654/test.js.txt)
добавил логов побольше, надо еще раз попасть в тупик и глянуть логи
потом остановишь main и надо запустить test на том экране

**Comment by Dexya** [comment]
![IMG_20220423_084619](https://user-images.githubusercontent.com/90963419/164869334-76021d24-4393-4d27-8141-432d56cf018c.jpg)

**Comment by yaldabaoth444** [comment]
не видит он кнопку "гонка", попробуй profile.ch.start.x, profile.ch.start.y увеличит на пару пикселей (2-4)

**Comment by Dexya** [comment]
Спасибо! Вроде работает отлично.
Ты извини, что нагрузил тебя)

**Comment by yaldabaoth444** [comment]
Отлично! без проблем, ты не мог бы еще раз выложить свои рабочие файлы. Попозже приведу их к единому виду. и выложу профиль под 2280x1080

**Comment by Dexya** [comment]
Да, конечно

**Comment by Dexya** [comment]
[2280x1080.zip](https://github.com/yaldabaoth444/Asphalt9/files/8549066/2280x1080.zip)
Там отключена Охота и не работает mp2 из за этого, надо со временем шаманить, я так понял.

**Comment by Dexya** [comment]
И рампы в охоте выключены

**Comment by yaldabaoth444** [comment]
Я обновил проект, перенес кое-какие параметры в конфиг.  теперь play.js не привязан к разрешению 2340. Я тебя упомянул если ты не против.

**Comment by yaldabaoth444** [comment]
вот кстати глянь как бот на винде Гран-при катает https://youtu.be/iwouaIRdATs

**Comment by Dexya** [comment]
Не против конечно.
Блин, круто! По идее на Андроиде так же можно сделать?
У меня чистый тач, без гибрида, на секунду бот меня сделал)

**Comment by yaldabaoth444** [comment]
можно если % трека определять, у меня на это много времени ушло

**Comment by Dexya** [comment]
Привет!
Вышла новая спец Охота. И зависает на данном экране 

[1651197002986](https://user-images.githubusercontent.com/90963419/165874304-785659fe-5106-48c3-ba04-7975616c5fd1.jpg)

**Comment by Dexya** [comment]
Auto.js говорит вот это 
![1651197002997](https://user-images.githubusercontent.com/90963419/165874497-a685d3d3-6c14-4de5-8453-086d0f01650e.jpg)
![1651197003003](https://user-images.githubusercontent.com/90963419/165874519-57c48b34-1ef4-4257-8309-669866a96d07.jpg)

**Comment by yaldabaoth444** [comment]
тебе нужно этот параметр обновить для своего разрешения
![image](https://user-images.githubusercontent.com/25618671/165887005-ef48dfcc-a939-4099-bc30-73c7832ef40e.png)
или можно любой другой уникальный пиксель для этого экрана найти
кнопка подсвечивается иногда, из-за этого могут быть задержки. может и на фон можно навестись,

**Comment by Dexya** [comment]
Теперь останавливается на выборе машин и ругается 
![IMG_20220429_122411](https://user-images.githubusercontent.com/90963419/165894358-ff8f3668-11ea-4124-a807-d51d2ea12aa0.jpg)

**Comment by yaldabaoth444** [comment]
ты не обновил play.js

**Comment by TsaiRueiEn** [comment]
15:01:06.283/E: Wrapped java.lang.IllegalArgumentException: x must be < bitmap.width() (file:/storage/emulated/0/脚本/play.js#2216)
Wrapped java.lang.IllegalArgumentException: x must be < bitmap.width()
    at isEquals (file:/storage/emulated/0/脚本/play.js:2216:0)
    at mpCheckState (file:/storage/emulated/0/脚本/play.js:1477:0)
    at file:/storage/emulated/0/脚本/play.js:312:0
    at /storage/emulated/0/脚本/main.js:95:0
I can't connect the scripts

**Comment by yaldabaoth444** [comment]
рестарт телефона не помогает? иногда autojs глючит так
то ли права слетают и он скриншот не может сделать

**Comment by TsaiRueiEn** [comment]
Is there any way to fix it?

**Comment by yaldabaoth444** [comment]
ups sorry another lang... Doesn't restarting the phone help? Sometimes autojs glitches like this
or the rights are lost and it can't take a screenshot.

**Comment by yaldabaoth444** [comment]
restart must fix ...Or you have the wrong coordinates for profile.common.token
