### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by dok187** [yaldabaoth444/Asphalt9#15]
the script has started, but it won't play itself

**Comment by yaldabaoth444** [comment]
what kind of scenario?
what resolution do you have?
what version of autojs?
what's in the logs?

**Comment by dok187** [comment]
Можно видос скинуть и увидишь сам)

**Comment by yaldabaoth444** [comment]
давай

**Comment by dok187** [comment]
Видос не записывается, вообщем дело обстаит так, запускаю срипт main.js пишит что есть 7 сееунд в игру зайти (я ее сворачиваю) происходит запуск, вылизает начать запись, нажимаю да, и все больше ни чего не происходит, иногда бывает он выбирает сетевую.

**Comment by yaldabaoth444** [comment]
дискорд есть?

**Comment by yaldabaoth444** [comment]
https://discord.com/invite/n56RNgztyj

**Comment by yaldabaoth444** [comment]
обнови, я добавил скрипт для теста

**Comment by dok187** [comment]
в дискорде твой ник Dark ? мой ник DasT1Qq
