### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by amerllica** [yaldabaoth444/Asphalt9#18]
My mobile phone is a `Black Shark 5 pro`, and its resolution is `1080x2400`.

After spending 6 hours tuning the configuration, when I try to play `device.js` but this error happens by toast:

```
Error: ReferenceError: "module"  is not defined. (/storage/emulated/0/Scripts/device.js#9)
```

Android version: 12
AutoJs: 4.1.1 Alpha2

**Comment by yaldabaoth444** [comment]
device.js is a non run file
run main.js

**Comment by yaldabaoth444** [comment]
or like this (remove last .txt extension)
[mp1infinite.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/11663696/mp1infinite.js.txt)

**Comment by amerllica** [comment]
Thanks for your help dear @yaldabaoth444 

By running `main.js` file now I get this error:

![IMAGE 2023-06-06 17:17:44 2](https://github.com/yaldabaoth444/Asphalt9/assets/10472437/578619c8-e20f-41a2-b80c-f7151ce812e4)

**Comment by amerllica** [comment]
Thanks for your help dear @yaldabaoth444 

It got started, but when it showed the permission for screen recording, suddenly it got crashed.

**Comment by yaldabaoth444** [comment]
Maybe autojs does not have the necessary permissions. take a screenshot of the settings

**Comment by yaldabaoth444** [comment]
[_screenshot.js.txt](https://github.com/yaldabaoth444/Asphalt9/files/11668661/_screenshot.js.txt)
does this script create files?

**Comment by amerllica** [comment]
I added the script and kicked off it for run, and this is the result:

https://github.com/yaldabaoth444/Asphalt9/assets/10472437/7a83314d-3190-4a85-bb5d-56f6886e8b08

**Comment by yaldabaoth444** [comment]
I think AutoJs4 is incompatible with the android version in terms of security. You need to port the project to AutoJs6. Unfortunately I support only the Windows version of the bot at the moment, due to the sale of the Android account.
..the bot still worked on Android 11

**Comment by amerllica** [comment]
Ok @yaldabaoth444, thanks for your support. it was an amazing experience. I will continue with real playing.
