### ISSUE TITLE
Script not selecting upper cars

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#2]
@yaldabaoth444  My script is not able to select the upper cars(15,17,19,13). It is selecting only lower cars(8,10,12). Can you please look into it if something is wrong? I restarted the device twice and it still has the same problem.
This has been happening for 8 hours. I thought restarting it will correct it but it still is the same.

[Selection](https://youtu.be/VCkvtOyHtmU)

**Comment by made101** [comment]
It solved automatically, I don't know what was wrong. I reinstalled the game and now everything works fine.

**Comment by Made101** [comment]
Now the script is not even electing a car.

**Comment by Made101** [comment]
Sorry, lad. I messed it up by changing the value of firstcar.x to 350. When I set everything to default, it all started working again

Everything was working fine until the script tried to select the upper cars, but it clicked on the Blueprint button(It happened with some lower cars also), So I changed the value of distance and distanceFlat to + 27 instead of +30, Now everything works fine. 


![Screenshot (74)](https://user-images.githubusercontent.com/77076813/116877594-c8645a80-ac3b-11eb-8e2d-e79cafa0a9e0.png)

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/116883424-06af4900-ac3f-11eb-9f7c-3e58d4f9aa4b.png)
check this
![image](https://user-images.githubusercontent.com/25618671/116884233-f055bd00-ac3f-11eb-9a9b-baab69b7258b.png)

**Comment by yaldabaoth444** [comment]
screenshots must be in png (loseless) format, otherwise the colors are distorted

**Comment by Made101** [comment]
> ![image](https://user-images.githubusercontent.com/25618671/116883424-06af4900-ac3f-11eb-9f7c-3e58d4f9aa4b.png)
> check this


Yeah, I didn't read this carefully. My mistake. When I set everything back to normal, it all started working again. I just needed to change the default value of 26 to 27. Now, everything is top notch.

**Comment by yaldabaoth444** [comment]
nice
