### ISSUE TITLE
UI Changes.

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#4]
A new play script is required for the car hunt. Can you please look into it? @yaldabaoth444

**Comment by yaldabaoth444** [comment]
It's not very clear yet. whether it's a separate special hunt or whether the regular hunt has moved

**Comment by made101** [comment]
> It's not very clear yet. whether it's a separate special hunt or whether the regular hunt has moved

I'm thinking it maybe a special hunt because the duration is 10 days and the packs now also has a limit.

**Comment by Made101** [comment]
But can you please make some changes or design a new play.js just for this type of hunt? If it's possible then please do so.

**Comment by Made101** [comment]
@yaldabaoth444 

![Screenshot (27)](https://user-images.githubusercontent.com/77076813/120812151-58aefb80-c56a-11eb-84e1-35e66775f8a0.png)

**Comment by yaldabaoth444** [comment]
Great, GL has released an update that fixes the teardrop notch.
So far I have made a temporary version, then we need to see how the next hunt comes out.
![image](https://user-images.githubusercontent.com/25618671/120854355-77c38280-c596-11eb-8b7b-111f3e77d3e7.png)
Parameters were added to the config
Now the hunt in the special section looks like this

**Comment by yaldabaoth444** [comment]
chse means  - car hunt special event
:)

**Comment by made101** [comment]
> chse means - car hunt special event
> :)

Hey, I tried it and everything works good now, thank you so much :)

**Comment by Made101** [comment]
> Great, GL has released an update that fixes the teardrop notch.
> So far I have made a temporary version, then we need to see how the next hunt comes out.
> ![image](https://user-images.githubusercontent.com/25618671/120854355-77c38280-c596-11eb-8b7b-111f3e77d3e7.png)
> Parameters were added to the config
> Now the hunt in the special section looks like this

Thank you so much for this, I faced two errors but solved them eventually. Thank you, let's see what the next hunts will be like
and yeah, they did release the update for the teardrop notch, it's much better now. :))
