### ISSUE TITLE
New settings

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#5]
Hey, I wanted to ask about the new settings you added in play.js and also did you update the CH script?

**Comment by Made101** [comment]
Also. Every time after RWR it keeps on clicking at these coordinates shown in the image (taken when the script running) instead of choosing the hunt. 
![Screenshot_20210621-222621_dac78dbb8b9d35e2ecbeaf4ec6ecff5b 1](https://user-images.githubusercontent.com/77076813/122800205-4a8a0a80-d2e0-11eb-93ea-2ee0644705e1.jpg)

**Comment by Made101** [comment]
@yaldabaoth444 Also, I wanted to know about those new folders(AD-B, AD-1, AD-S)

**Comment by yaldabaoth444** [comment]
> Hey, I wanted to ask about the new settings you added in play.js and also did you update the CH script?

the new settings apply to auto selection in modes "ordinary" and "flat", regardless of where they are used in MP or CarHunt

**Comment by Made101** [comment]
> > Hey, I wanted to ask about the new settings you added in play.js and also did you update the CH script?
> 
> the new settings apply to auto selection in modes "ordinary" and "flat", regardless of where they are used in MP or CarHunt

Oh Okay. Thank you. Also the above error I was getting was because of me modifying the script, when I ran with your code, it all works perfectly now. Thank you :)

**Comment by yaldabaoth444** [comment]
> @yaldabaoth444 Also, I wanted to know about those new folders(AD-B, AD-1, AD-S)

this is an experimental infinite-advertising function for collecting Y,B,R tokens

**Comment by Made101** [comment]
Oh Okay

**Comment by yaldabaoth444** [comment]
the main goal is to get blue tokens with a 10% probability

**Comment by Made101** [comment]
That sounds good. I heard about it. Good luck :)
Also Thank you for adding the new fuel selection method for MP2 :))

**Comment by yaldabaoth444** [comment]
No problem, you're welcome to use it.

**Comment by Made101** [comment]
Thank you so much :))

**Comment by Made101** [comment]
Also, If you need my mail, just tag me. Imma close this for now. Thank you for the scripts :))
