### ISSUE TITLE
Some problems in MP2

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#6]
Hey, So Fuel selection in MP2 works fine for every car except 5 and 6. Can you please check what is the problem here?

[NoFuel](https://youtu.be/u7XSYt5BmEg)

**Comment by Made101** [comment]
Is this on purpose or just an error on my side? @yaldabaoth444

**Comment by yaldabaoth444** [comment]
temporary solution:
try comment line with toast("<---");
at 1421 and 1471 in play.js
Apparently the tooltip doesn't have time to disappear
or you can add a delay after scrolling
P.S. that solves the problem with the fifth car, I have the sixth car on refueling for now

**Comment by Made101** [comment]
Yeah. It solved it for the 5th car, 6th car still no fuel.

**Comment by Made101** [comment]
Btw, how many milestones were you able to complete in MP2? I didn't do MP2 at all because of CarHunt.

**Comment by yaldabaoth444** [comment]
13k+ at the moment

**Comment by Made101** [comment]
That's great. If it had 2-3 more cars, it would've been much more.

**Comment by yaldabaoth444** [comment]
try update play.js

**Comment by Made101** [comment]
It's working perfectly now! :)
Also, I had one more problem.
![Screenshot_20210622-114001_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/123279469-819d2d80-d525-11eb-9b8e-d2e8cde9699f.jpg)

In this picture, the script recognises the OK button but what happens is It swipes first and then instantly tries to click on the OK button while it's moving which doesn't work because the game doesn't register two taps at once (The swiping as well as clicking on the OK button). This also means that I'm constantly stuck in a loop  where script tries to click the OK button while swiping but fails. Any solutions for this?

**Comment by Made101** [comment]
Also the MP2 Fuel check works perfectly now :) @yaldabaoth444

**Comment by yaldabaoth444** [comment]
> It's working perfectly now! :)
> Also, I had one more problem.
> ![Screenshot_20210622-114001_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/123279469-819d2d80-d525-11eb-9b8e-d2e8cde9699f.jpg)
> 
> In this picture, the script recognises the OK button but what happens is It swipes first and then instantly tries to click on the OK button while it's moving which doesn't work because the game doesn't register two taps at once (The swiping as well as clicking on the OK button). This also means that I'm constantly stuck in a loop where script tries to click the OK button while swiping but fails. Any solutions for this?

I think I fixed that too, I should have put a delay
line 1915

**Comment by Made101** [comment]
> > It's working perfectly now! :)
> > Also, I had one more problem.
> > ![Screenshot_20210622-114001_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/123279469-819d2d80-d525-11eb-9b8e-d2e8cde9699f.jpg)
> > In this picture, the script recognises the OK button but what happens is It swipes first and then instantly tries to click on the OK button while it's moving which doesn't work because the game doesn't register two taps at once (The swiping as well as clicking on the OK button). This also means that I'm constantly stuck in a loop where script tries to click the OK button while swiping but fails. Any solutions for this?
> 
> I think I fixed that too, I should have put a delay
> line 1915

Oh yeah. Its all good now. Just checked. Thank you :))

**Comment by Made101** [comment]
Also a few days ago, If I remember correctly I ran the main script with CarHunt enabled and went to sleep and somehow woke up to 39 tokens, looked like it bought credits with tokens, Luckily, CC refunded my 3.8k tokens because they were spent on credits. Lmao. Wild.

**Comment by Made101** [comment]
That was wild, haha. Anyway, Thanks for the changes :))

**Comment by yaldabaoth444** [comment]
:)
