### ISSUE TITLE
请教正确的使用姿势

### ISSUE THREAD

**Issue by shawtung** [yaldabaoth444/Asphalt9#7]
捣鼓了很长时间还是啥都跑不起来，mpCheckState 里的 isGames 的判断都有问题。readme 的内容太少了，旧仓库的教程我也搞过一遍，也大概知道这个仓库改了些什么。我看 adClose 里及 issue 里的图片都是俄文版本的，是要有啥前置条件吗？

**Comment by yaldabaoth444** [comment]
When the algorithm gets stuck (mpCheckState returns "unknow") it tries to click on the button with the image from the AdCloser folder, hoping to close the popup ad
....in the AdCloser folder you can replace all the files with your variants

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/126080089-1dcbab80-76e6-4240-8aa9-28416d9bf7a9.png)
made for cases where there might be an MP3

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/126080369-f8f83c08-b43d-49ff-bd8f-83b35005f279.png)
To check, you can run this code on the desired screen (see test.js) it will show which primitives it detects

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/126080383-cc26a5ce-13fa-426c-921a-5bc205c268ea.png)
Based on the set of primitives it judges which state to give out

**Comment by yaldabaoth444** [comment]
Also the graphics settings can affect the recognition.I have selected standard (no performance or high quality)

**Comment by yaldabaoth444** [comment]
![image](https://user-images.githubusercontent.com/25618671/126080916-b9bb3ddb-9996-48cf-a504-cc1f28115c7d.png)
like this

**Comment by yaldabaoth444** [comment]
Have you solved your problem? Have you seen this section /readme/Explanation of settings in pictures/ ?

**Comment by shawtung** [comment]
> Have you solved your problem? Have you seen this section /readme/Explanation of settings in pictures/ ?

Thank you very much~ I'll try your solution after today's work~ :) and give you feedback in time~
