### ISSUE TITLE
Unable to select some cars in current MP1

### ISSUE THREAD

**Issue by nujabse** [yaldabaoth444/Asphalt9#9]
In the current MP1, all the cars are available in bronze, silver and gold levels. That is to say, you can pick any car in any level. However, when I tried to let the script choose cars with index higher than `30`, the script can not correctly find and choose the car, showing "the car has no fuel". How can I adapt the script to make it work again in the current MP1 ?

**Comment by yaldabaoth444** [comment]
1) read this post https://github.com/yaldabaoth444/Asphalt9/issues/2
2) run this script from this position 
![image](https://user-images.githubusercontent.com/25618671/148247541-3f5ce33c-0783-4fa9-9774-10f68760409e.png)
and check where the coordinates point after the garage shifts to the selected car. you may need to adjust the inertia value
![image](https://user-images.githubusercontent.com/25618671/148247899-c465cfc1-e42c-4362-8428-81c4619fa362.png)

**Comment by yaldabaoth444** [comment]
and update play.js first

**Comment by nujabse** [comment]
Thanks for the reply! I updated to the latest play.js, and adjusted the `inertia` to `25`. Now the script can correctly choose cars with index number up to 50.  I tried to let it choose car with index number of 64 but failed. Maybe I stilll need to adjust the inertial values, but that's just okay for now. Thanks for your timely help!

**Comment by yaldabaoth444** [comment]
most likely you need a floating point value, with each shift the unaccounted correction accumulates

**Comment by yaldabaoth444** [comment]
They have an interface made by floating elements that adjusts to the current resolution and aspect ratio of the device, so it is not pixel perfect

**Comment by yaldabaoth444** [comment]
In the windows version of the bot I select cars not by location but by name and it is a faster and less costly option in terms of configuration

**Comment by nujabse** [comment]
Yes, I agree that the car selection mode used now is a bit slow. Hope that the selection of cars by car name can be ported to the script.
